services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: rental-home-api
    tty: true
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - rental-home-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: rental-home-worker
    tty: true
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - rental-home-network

  database:
    image: postgres:15
    container_name: rental-home-database
    volumes:
      - rental-home-database-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      TZ: "UTC"
    networks:
      - rental-home-network

  localstack:
    image: localstack/localstack
    container_name: rental-home-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - GATEWAY_LISTEN=0.0.0.0:4566
    volumes:
      - rental-home-localstack-data:/var/lib/localstack # Persist data
      - rental-home-localstack-docker-sock:/var/run/docker.sock
    networks:
      - rental-home-network

  redis:
    image: redis/redis-stack:latest
    container_name: rental-home-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - rental-home-redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    environment:
      REDIS_ARGS: "--requirepass redispass"
    networks:
      - rental-home-network

volumes:
  rental-home-database-data:
  rental-home-localstack-data:
  rental-home-localstack-docker-sock:
  rental-home-redis_data:

networks:
  rental-home-network:
      driver: bridge
